CREATE TABLE IF NOT EXISTS `syllabus` {
	`S.N.` INT(4) NOT NULL AUTO_INCREMENT,
	`SCHEME` INT(4) NOT NULL,
	`BRANCH` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`SEMESTER` INT(1) NOT NULL
	PRIMARY KEY (`S.N.`),
} ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;