
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


-- Database: `studentportal`
--

-- --------------------------------------------------------
CREATE Database studentportal;
USE studentportal;
--
-- Table structure for table `student registration`
--

CREATE TABLE IF NOT EXISTS `student_regist` (
  `ADMISSION_NO` varchar(10) COLLATE utf8_unicode_ci NOT NULL UNIQUE,
  `FULL_NAME` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `BRANCH` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PASSWORD` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `EMAIL` varchar(30) COLLATE utf8_unicode_ci NOT NULL UNIQUE,
  PRIMARY KEY (`ADMISSION_NO`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `personal detail student`
--

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `student_personal_detail` (
  `ADMISSION_NO` varchar(10) COLLATE utf8_unicode_ci NOT NULL UNIQUE,
  `GAURDIAN_NAME` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `DATE_OF_BIRTH` date NOT NULL,
  `MOBILE_NO_SELF` bigint(10) NOT NULL UNIQUE,
  `MOBILE_NO_GUARDIAN` bigint(10) NOT NULL,
  `SCHEME` int(4) NOT NULL,
  `CURRENT_SEMESTER` int(1) NOT NULL,
  `REGISTRATION_NO` bigint(8) NOT NULL UNIQUE,
  `GENDER` char(1) COLLATE utf8_unicode_ci NOT NULL,
  `LOCAL_ADDRESS` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `IMAGE` varchar(350) COLLATE utf8_unicode_ci NOT NULL,
  `PERMANENT_ADDRESS` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `BRANCH` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`REGISTRATION_NO`),
  FOREIGN KEY (`ADMISSION_NO`) REFERENCES `student_regist`(`ADMISSION_NO`)
  ON DELETE CASCADE 
  ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `faculty registration`
--

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `faculty_regist` (
  `EMPLOYEE_ID` varchar(10) COLLATE utf8_unicode_ci NOT NULL UNIQUE,
  `FULL_NAME` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `BRANCH` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `PASSWORD` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `EMAIL` varchar(50) COLLATE utf8_unicode_ci NOT NULL UNIQUE,
  PRIMARY KEY (`EMPLOYEE_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `attendance`
--

-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendance` (
  `REGISTRATION_NO` bigint(8) NOT NULL UNIQUE,
  `MONTH_1` float(5) ,
  `MONTH_2` float(5) ,
  `MONTH_3` float(5) ,
  `MONTH_4` float(5) ,
  `MONTH_5` float(5) ,
  `MONTH_6` float(5) ,
  `FINAL` float(5) ,
  FOREIGN KEY (`REGISTRATION_NO`) REFERENCES `student_personal_detail`(`REGISTRATION_NO`)
  ON DELETE CASCADE 
  ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `academics`
--

-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `academics` (
  `REGISTRATION_NO` bigint(8) NOT NULL UNIQUE,
  `SUBJECT_CODE` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `INTERNAL_1` int(2) ,
  `INTERNAL_2` int(2) ,
  `ASSIGNMENT_1` int(2) ,
  `ASSIGNMENT_2` int(2) ,
  `ATTENDANCE` int(2) ,
  `SESSIONAL` int(2) ,
  PRIMARY KEY (`REGISTRATION_NO`,`SUBJECT_CODE`),
  FOREIGN KEY (`REGISTRATION_NO`) REFERENCES `student_personal_detail` (`REGISTRATION_NO`)
  ON DELETE CASCADE 
  ON UPDATE CASCADE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



-- --------------------------------------------------------

--
-- Table structure for table `documents`
--

-- --------------------------------------------------------

CREATE TABLE IF NOT EXISTS `documents` (
  `REGISTRATION_NO` bigint(8) NOT NULL UNIQUE,
  `10TH` varchar(350) COLLATE utf8_unicode_ci ,
  `12TH` varchar(350) COLLATE utf8_unicode_ci ,
  `RESUME` varchar(350) COLLATE utf8_unicode_ci,
  `FEE_RECEIPT` varchar(350) COLLATE utf8_unicode_ci ,
  FOREIGN KEY (`REGISTRATION_NO`) REFERENCES `student_personal_detail` (`REGISTRATION_NO`)
  ON DELETE CASCADE
  ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `documents`
--

-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `syllabus` {
	`S.N.` INT(4) NOT NULL AUTO_INCREMENT,
	`BRANCH` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`SEMESTER` INT(1) NOT NULL,
  `SUBJECT_CODE` VARCHAR(10) NOT NULL,
  `SUBJECT_NAME` VARCHAR(150) NOT NULL,
	PRIMARY KEY (`S.N.`),
} ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `syllabus`(`S.N.`,`BRANCH`,`SEMESTER`,`SUBJECT_CODE`,`SUBJECT_NAME`)
VALUES (NULL,'EEE','1','AS1101A','CALCULAS'),
(NULL,'EEE','1','GE1102A','ENGINEERING PHYSICS'),
(NULL,'EEE','1','GE1103A','ENGINEERING MECHANICS'),
(NULL,'EEE','1','GE1104A','BASIC CIVIL ENGINEERING'),
(NULL,'EEE','1','GE1105A','BASIC MECHANICAL ENGINEERING'),
(NULL,'EEE','1','HS1106A','TCP'),
(NULL,'EEE','2','GE1201A','COMPUTER PROGRAMMING'),
(NULL,'EEE','2','AS1202A','ENGINEERING CHEMISTRY'),
(NULL,'EEE','2','GE1203A','ENGINEERING GRAPHICS'),
(NULL,'EEE','2','GE1204A','BASIC ELECTRICAL ENGINEERING'),
(NULL,'EEE','2','GE1205A','BASIC ELECTRONICS ENGINEERING'),
(NULL,'EEE','2','AS1206A','ENVIRONMENTAL STUDIES'),
(NULL,'EEE','3','AS1301','LINEAR ALGEBRA'),
(NULL,'EEE','3','EE1302','FLUID MACHINARY'),
(NULL,'EEE','3','EE1303','CIRCUIT AND NETWORK'),
(NULL,'EEE','3','EE1304','ELECTRICAL MEASUREMENT AND MEASURING INSTRUMENT'),
(NULL,'EEE','3','EE1305','ELECTRONICS DEVICE AND CIRCUITS'),
(NULL,'EEE','3','EE1306','ELECTRONICS MACHINES I'),
(NULL,'EEE','4','AS1401','COMPLEX VARIABLES AND PARTIAL DIFFERENTIAL EQUATIONS'),
(NULL,'EEE','4','EE1402','CIRCUITS,SIGNAL& SYSTEM'),
(NULL,'EEE','4','EE1403','ELECTRICAL MACHINES II'),
(NULL,'EEE','4','EE1404','ELECTRICAL ENGINEERING MATERIALS'),
(NULL,'EEE','4','EE1405','DIGITAL ELECTRONICS'),
(NULL,'EEE','4','EE1406','POWER ELECTRONICS'),
(NULL,'ECE','1','AS1101B','CALCULAS'),
(NULL,'ECE','1','GE1102B','ENGINEERING PHYSICS'),
(NULL,'ECE','1','GE1103B','ENGINEERING MECHANICS'),
(NULL,'ECE','1','GE1104B','BASIC CIVIL ENGINEERING'),
(NULL,'ECE','1','GE1105B','BASIC MECHANICAL ENGINEERING'),
(NULL,'ECE','1','HS1106B','TCP'),
(NULL,'ECE','2','GE1201B','COMPUTER PROGRAMMING'),
(NULL,'ECE','2','AS1202B','ENGINEERING CHEMISTRY'),
(NULL,'ECE','2','GE1203B','ENGINEERING GRAPHICS'),
(NULL,'ECE','2','GE1204B','BASIC ELECTRICAL ENGINEERING'),
(NULL,'ECE','2','GE1205B','BASIC ELECTRONICS ENGINEERING'),
(NULL,'ECE','2','AS1206B','ENVIRONMENTAL STUDIES'),
(NULL,'ECE','3','AS1301','LINEAR ALGEBRA'),
(NULL,'ECE','3','EC1302','DISCRETE COMPUTATIONAL STRUCTURE'),
(NULL,'ECE','3','EC1303','NETWORK THEORY'),
(NULL,'ECE','3','EC1304','DIGITAL ELECTRONICS'),
(NULL,'ECE','3','EC1305','SOLID STATE ELECTRONICS'),
(NULL,'ECE','3','EC1306','ELECTRONIC CIRCUIT I'),
(NULL,'ECE','4','AS1401','COMPLEX VARIABLES AND PARTIAL DIFFERENTIAL EQUATIONS'),
(NULL,'ECE','4','EC1402','MICROPROCESSOR ARCHITECTURES AND PROGRAMMING'),
(NULL,'ECE','4','EC1403','ELECTRONICS CIRCUITS II'),
(NULL,'ECE','4','EC1404','SIGNAL AND SYSTEM'),
(NULL,'ECE','4','EC1405','COMMUNICATION ENGINEERING'),
(NULL,'ECE','4','EC1406','DIGITAL SYSTEM DESIGN'),
(NULL,'CSE','1','AS1101B','CALCULAS'),
(NULL,'CSE','1','GE1102B','ENGINEERING PHYSICS'),
(NULL,'CSE','1','GE1103B','ENGINEERING MECHANICS'),
(NULL,'CSE','1','GE1104B','BASIC CIVIL ENGINEERING'),
(NULL,'CSE','1','GE1105B','BASIC MECHANICAL ENGINEERING'),
(NULL,'CSE','1','HS1106B','TCP'),
(NULL,'CSE','2','GE1201B','COMPUTER PROGRAMMING'),
(NULL,'CSE','2','AS1202B','ENGINEERING CHEMISTRY'),
(NULL,'CSE','2','GE1203B','ENGINEERING GRAPHICS'),
(NULL,'CSE','2','GE1204B','BASIC ELECTRICAL ENGINEERING'),
(NULL,'CSE','2','GE1205B','BASIC ELECTRONICS ENGINEERING'),
(NULL,'CSE','2','AS1206B','ENVIRONMENTAL STUDIES'),
(NULL,'CSE','3','AS1301','LINEAR ALGEBRA'),
(NULL,'CSE','3','CS1302','LOGIC DESIGN'),
(NULL,'CSE','3','CS1303','DISCRETE COMPUTATIONAL STRUCTURE'),
(NULL,'CSE','3','CS1304','OBJECT ORIENTED PROGRAMMING'),
(NULL,'CSE','3','CS1305','PRINCIPAL OF PROGRAMMING LANGUAGE'),
(NULL,'CSE','3','CS1306','DATA AND COMPUTER COMMUNICATION'),
(NULL,'CSE','4','AS1401','COMPLEX VARIABLES AND PARTIAL DIFFERENTIAL EQUATIONS'),
(NULL,'CSE','4','CS1402','MICROPROCESSORS'),
(NULL,'CSE','4','CS1403','COMPUTER ARCHITECTURE AND ORAGNIZATION'),
(NULL,'CSE','4','CS1404','AUTOMATA LANGUAGE AND COMPUTATIONS'),
(NULL,'CSE','4','CS1405','DATA STRUCTURE AND ALGORITHMS'),
(NULL,'CSE','4','CS1406','DATABASE MANAGEMENT SYSTEM'),
(NULL,'CE','1','AS1101A','CALCULAS'),
(NULL,'CE','1','GE1102A','ENGINEERING PHYSICS'),
(NULL,'CE','1','GE1103A','ENGINEERING MECHANICS'),
(NULL,'CE','1','GE1104A','BASIC CIVIL ENGINEERING'),
(NULL,'CE','1','GE1105A','BASIC MECHANICAL ENGINEERING'),
(NULL,'CE','1','HS1106A','TCP'),
(NULL,'CE','2','GE1201A','COMPUTER PROGRAMMING'),
(NULL,'CE','2','AS1202A','ENGINEERING CHEMISTRY'),
(NULL,'CE','2','GE1203A','ENGINEERING GRAPHICS'),
(NULL,'CE','2','GE1204A','BASIC ELECTRICAL ENGINEERING'),
(NULL,'CE','2','GE1205A','BASIC ELECTRONICS ENGINEERING'),
(NULL,'CE','2','AS1206A','ENVIRONMENTAL STUDIES'),
(NULL,'CE','3','AS1301','LINEAR ALGEBRA'),
(NULL,'CE','3','CE1302','SURVEYING I'),
(NULL,'CE','3','CE1303','STRENGTH OF MATERIAL'),
(NULL,'CE','3','CE1304','CONCRETE TECHNOLOGY'),
(NULL,'CE','3','CE1305','FLUID MECHANICS I'),
(NULL,'CE','3','CE1306','BUILDING TECHNOLOGY'),
(NULL,'CE','4','AS1401','COMPLEX VARIABLES AND PARTIAL DIFFERENTIAL EQUATIONS'),
(NULL,'CE','4','CE1402','SURVEYING II'),
(NULL,'CE','4','CE1403','ANALYSIS OF DETERMINATE STRUCTURES'),
(NULL,'CE','4','CE1404','ENGINEERING GEOLOGY AND SEISMOLOGY'),
(NULL,'CE','4','CE1405','FLUID MECHANICS II'),
(NULL,'CE','4','CE1406','BUILDING PLANNING AND DRAWING'),
(NULL,'ME','1','AS1101A','CALCULAS'),
(NULL,'ME','1','GE1102A','ENGINEERING PHYSICS'),
(NULL,'ME','1','GE1103A','ENGINEERING MECHANICS'),
(NULL,'ME','1','GE1104A','BASIC CIVIL ENGINEERING'),
(NULL,'ME','1','GE1105A','BASIC MECHANICAL ENGINEERING'),
(NULL,'ME','1','HS1106A','TCP'),
(NULL,'ME','2','GE1201A','COMPUTER PROGRAMMING'),
(NULL,'ME','2','AS1202A','ENGINEERING CHEMISTRY'),
(NULL,'ME','2','GE1203A','ENGINEERING GRAPHICS'),
(NULL,'ME','2','GE1204A','BASIC ELECTRICAL ENGINEERING'),
(NULL,'ME','2','GE1205A','BASIC ELECTRONICS ENGINEERING'),
(NULL,'ME','2','AS1206A','ENVIRONMENTAL STUDIES'),
(NULL,'ME','3','AS1301','LINEAR ALGEBRA'),
(NULL,'ME','3','ME1302','ELECTRICAL TECHNOLOGY'),
(NULL,'ME','3','ME1303','MECHANICS OF SOLIDS'),
(NULL,'ME','3','ME1304','FLUID MECHANICS'),
(NULL,'ME','3','ME1305','METALLURGY AND MATERIAL SCIENCE'),
(NULL,'ME','3','ME1306','MACHINE DRAWING'),
(NULL,'ME','4','AS1401','COMPLEX VARIABLES AND PARTIAL DIFFERENTIAL EQUATIONS'),
(NULL,'ME','4','ME1402','METROLOGY AND INSTRUMENTATION'),
(NULL,'ME','4','ME1403','MECHATRONICS'),
(NULL,'ME','4','ME1404','APPLIED THERMODYNAMICS'),
(NULL,'ME','4','ME1405','MANUFACTURING PROCESSES'),
(NULL,'ME','4','ME1406','HYDRAULIC MACHINERY'),
(NULL,'IT','1','AS1101B','CALCULAS'),
(NULL,'IT','1','GE1102B','ENGINEERING PHYSICS'),
(NULL,'IT','1','GE1103B','ENGINEERING MECHANICS'),
(NULL,'IT','1','GE1104B','BASIC CIVIL ENGINEERING'),
(NULL,'IT','1','GE1105B','BASIC MECHANICAL ENGINEERING'),
(NULL,'IT','1','HS1106B','TCP'),
(NULL,'IT','2','GE1201B','COMPUTER PROGRAMMING'),
(NULL,'IT','2','AS1202B','ENGINEERING CHEMISTRY'),
(NULL,'IT','2','GE1203B','ENGINEERING GRAPHICS'),
(NULL,'IT','2','GE1204B','BASIC ELECTRICAL ENGINEERING'),
(NULL,'IT','2','GE1205B','BASIC ELECTRONICS ENGINEERING'),
(NULL,'IT','2','AS1206B','ENVIRONMENTAL STUDIES'),
(NULL,'IT','3','AS1301','LINEAR ALGEBRA'),
(NULL,'IT','3','IT1302','LOGIC DESIGN AND ELECTRONICS CIRCUIT'),
(NULL,'IT','3','IT1303','DISCRETE COMPUTATIONAL STRUCTURES'),
(NULL,'IT','3','IT1304','OBJECT ORIENTED PROGRAMMING'),
(NULL,'IT','3','IT1305','COMPUTER ORGANIZATION'),
(NULL,'IT','3','IT1306','DATA COMMUNICATION AND NETWORKING'),
(NULL,'IT','4','AS1401','COMPLEX VARIABLES AND PARTIAL DIFFERENTIAL EQUATIONS'),
(NULL,'IT','4','IT1402','FLAT'),
(NULL,'IT','4','IT1403','SYSTEM PROGRAMMING'),
(NULL,'IT','4','IT1404','MICROPROCESSOR'),
(NULL,'IT','4','IT1405','DATA STRUCTURE AND ALGORITHM'),
(NULL,'IT','4','IT1406','DATABASE MANAGEMENT SYSTEM');
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
